# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'secret' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qris-sdk-new-1
  # Pods for astrapay
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'Fabric'
  pod 'MaterialComponents/Snackbar'
  pod 'Crashlytics', '~>  3.10'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'MoEngage-iOS-SDK' , '~>7.0.4'
  pod 'MOGeofence' , '~>3.0.1'
  pod 'MoEngageInApp','~> 2.0.0'
  pod 'SVProgressHUD'
  pod 'MYPassthrough'
  pod 'Sejima'
  pod 'AppsFlyerFramework'
  pod 'lottie-ios'
  pod 'Alamofire'
  # pod 'SDWebImage'
  pod 'SkeletonView'


  #guntur
  pod 'TTSegmentedControl', '~>0.4.9'

  #refactor
  pod 'RxSwift'

  target 'secretTests' do
    # Pods for testing
  end

end

target 'testingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testingApp

  target 'testingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testingAppUITests' do
    # Pods for testing
  end

end
